#encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Player.create(name: 'Esteban Andrés Suárez',shirt: 'Esteban', realteam: 'ALM', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Julián Cuesta Díaz',shirt: 'Julián', realteam: 'ALM', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Marco Natanael Torsiglieri',shirt: 'Torsiglieri', realteam: 'ALM', position: 'DEF', nacionality: 'ARG',transferable: false)
Player.create(name: 'Marcelo Andŕes Silva Fernández',shirt: 'Marcelo Silva', realteam: 'ALM', position: 'DEF', nacionality: 'URU',transferable: false)
Player.create(name: 'Hans Aléxis Martínez Cabrera',shirt: 'Hans Martínez', realteam: 'ALM', position: 'DEF', nacionality: 'CHI',transferable: false)
Player.create(name: 'Ángel Trujillo Canorea',shirt: 'Trujillo', realteam: 'ALM', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Sebastián Dubarbier',shirt: 'Dubarbier', realteam: 'ALM', position: 'DEF', nacionality: 'ARG',transferable: false)
Player.create(name: 'José Manuel Jiménez Ortiz',shirt: 'Mané', realteam: 'ALM', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Rafael Ramos Lozano',shirt: 'Rafita', realteam: 'ALM', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Nelson Augusto Tomar Ramos',shirt: 'Nelson', realteam: 'ALM', position: 'DEF', nacionality: 'POR',transferable: false)
Player.create(name: 'Marcos Tébar Ramiro',shirt: 'Marcos Tébar', realteam: 'ALM', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'José Antonio García Rabasco',shirt: 'Verza', realteam: 'ALM', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Ramon Olamilekan Azeez',shirt: 'Azeez', realteam: 'ALM', position: 'MED', nacionality: 'NIG',transferable: false)
Player.create(name: 'Miguel Ángel García Pérez-Roldán',shirt: 'Corona', realteam: 'ALM', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Fernando Soriano Marcos',shirt: 'Soriano', realteam: 'ALM', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Aleix Vidal Parreu',shirt: 'Aleix Vidal', realteam: 'ALM', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Hélder Jorge Leal Rodrigues Barbosa',shirt: 'Hélder Barbosa', realteam: 'ALM', position: 'MED', nacionality: 'POR',transferable: false)
Player.create(name: 'Jesús Joaquín Fernández Sáez de la Torre',shirt: 'Suso', realteam: 'ALM', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jonathan Sundy Zongo',shirt: 'Zongo', realteam: 'ALM', position: 'MED', nacionality: 'BUR',transferable: false)
Player.create(name: 'Óscar Díaz González',shirt: 'Óscar Díaz', realteam: 'ALM', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Rodrigo Ríos Lozano',shirt: 'Rodri', realteam: 'ALM', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jaime Jiménez Merlo',shirt: 'Jaime Jiménez', realteam: 'VAD', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Diego Marino Villar',shirt: 'Marino', realteam: 'VAD', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Heinz Bartmettler',shirt: 'Bartmettler', realteam: 'VAD', position: 'DEF', nacionality: 'DOM',transferable: false)
Player.create(name: 'Marc Valiente Hernández',shirt: 'Valiente', realteam: 'VAD', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jesús Rueda Ambrosio',shirt: 'Rueda', realteam: 'VAD', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Stefan Mitrovic',shirt: 'Mitrovic', realteam: 'VAD', position: 'DEF', nacionality: 'SER',transferable: false)
Player.create(name: 'Carlos González Pena',shirt: 'Pena', realteam: 'VAD', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Zakaria Bergdich',shirt: 'Bergdich', realteam: 'VAD', position: 'DEF', nacionality: 'MAR',transferable: false)
Player.create(name: 'Antonio Rukavina',shirt: 'Rukavina', realteam: 'VAD', position: 'DEF', nacionality: 'SER',transferable: false)
Player.create(name: 'Gilberto García Olarte',shirt: 'Alcatraz', realteam: 'VAD', position: 'DEF', nacionality: 'COL',transferable: false)
Player.create(name: 'Javier Baraja Vegas',shirt: 'Baraja', realteam: 'VAD', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Lluis Sastre Reus',shirt: 'Sastre', realteam: 'VAD', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Álvaro Rubio Robles',shirt: 'Álvaro Rubio', realteam: 'VAD', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Víctor Pérez Alonso',shirt: 'Víctor Pérez', realteam: 'VAD', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Fausto Rossi',shirt: 'Rossi', realteam: 'VAD', position: 'MED', nacionality: 'ITA',transferable: false)
Player.create(name: 'Óscar Javier González Marcos',shirt: 'Óscar', realteam: 'VAD', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Julián Omar Ramos Suárez',shirt: 'Omar', realteam: 'VAD', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Valdet Rama',shirt: 'Rama', realteam: 'VAD', position: 'MED', nacionality: 'ALB',transferable: false)
Player.create(name: 'Daniel Larsson',shirt: 'Larsson', realteam: 'VAD', position: 'DEL', nacionality: 'SUE',transferable: false)
Player.create(name: 'Jeffrén Suárez Bermúdez',shirt: 'Jeffrén', realteam: 'VAD', position: 'DEL', nacionality: 'VEN',transferable: false)
Player.create(name: 'Humberto Segundo Osorio Botello',shirt: 'Osorio', realteam: 'VAD', position: 'DEL', nacionality: 'COL',transferable: false)
Player.create(name: 'Javier Guerra Rodríguez',shirt: 'Javi Guerra', realteam: 'VAD', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Mateus Alberto Contreiras Gonçalves',shirt: 'Manucho', realteam: 'VAD', position: 'DEL', nacionality: 'ANG',transferable: false)
Player.create(name: 'Keylor Antonio Navas Gamboa',shirt: 'Keylor Navas', realteam: 'LEV', position: 'POR', nacionality: 'CRI',transferable: false)
Player.create(name: 'Javier Jiménez Camarero',shirt: 'Javi Jiménez', realteam: 'LEV', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'David Navarro Pedrós',shirt: 'David Navarro', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Héctor Rodás Ramírez',shirt: 'Héctor Rodás', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Loukas Vyntra',shirt: 'Vyntra', realteam: 'LEV', position: 'DEF', nacionality: 'GRE',transferable: false)
Player.create(name: 'Issam El-Adoua',shirt: 'El Adoua', realteam: 'LEV', position: 'DEF', nacionality: 'MAR',transferable: false)
Player.create(name: 'Juan Francisco García García',shirt: 'Juanfran', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Nikolaos Karabelas',shirt: 'Karabelas', realteam: 'LEV', position: 'DEF', nacionality: 'GRE',transferable: false)
Player.create(name: 'Pedro López Múnoz',shirt: 'Pedro López', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Alberto Gómez Fernández',shirt: 'Nagore', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Miguel Pallardó González',shirt: 'Pallardó', realteam: 'LEV', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Sergio da Silva Pinto',shirt: 'Sergio Pinto', realteam: 'LEV', position: 'MED', nacionality: 'POR',transferable: false)
Player.create(name: 'Mohammed Lamine Sissoko',shirt: 'Sissoko', realteam: 'LEV', position: 'MED', nacionality: 'MAL',transferable: false)
Player.create(name: 'Papakouli Diop',shirt: 'Papakouli Diop', realteam: 'LEV', position: 'MED', nacionality: 'SEN',transferable: false)
Player.create(name: 'Simao Mate Junior',shirt: 'Simao', realteam: 'LEV', position: 'MED', nacionality: 'MOZ',transferable: false)
Player.create(name: 'Jordi Xumetra Feliu',shirt: 'Xumetra', realteam: 'LEV', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Pedro Ríos Maestre',shirt: 'Pedro Ríos', realteam: 'LEV', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Andreas Ivanschitz',shirt: 'Ivanschitz', realteam: 'LEV', position: 'MED', nacionality: 'AUT',transferable: false)
Player.create(name: 'Rubén García Santos',shirt: 'Rubén', realteam: 'LEV', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Nabil El-Zhar',shirt: 'El Zhar', realteam: 'LEV', position: 'DEL', nacionality: 'MAR',transferable: false)
Player.create(name: 'Víctor Casadesús Castano',shirt: 'Víctor Casadesús', realteam: 'LEV', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'David Barral Torres',shirt: 'David Barral', realteam: 'LEV', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Ángel Luis Rodríguez Díaz',shirt: 'Ángel', realteam: 'LEV', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Papa Babacar Diawara',shirt: 'Babá', realteam: 'LEV', position: 'DEL', nacionality: 'SEN',transferable: false)
Player.create(name: 'Asier Riesgo Unamuno',shirt: 'Riesgo', realteam: 'OSA', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Andrés Fernández Moreno',shirt: 'Andrés Fernández', realteam: 'OSA', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Miguel Flano Bezunartea',shirt: 'Flano', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Alejandro Arribas Garrido',shirt: 'Arribas', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jordan Lotiès',shirt: 'Lotiès', realteam: 'OSA', position: 'DEF', nacionality: 'FRA',transferable: false)
Player.create(name: 'Joan Oriol Gracia',shirt: 'Oriol', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Eneko Satrústegui Plano',shirt: 'Satrústegui', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Marc Bertrán Vilanova',shirt: 'Bertrán', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Oier Sanjurjo Maté',shirt: 'Oier', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Damià Abella Páez',shirt: 'Damià', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Manuel Ortiz Toribio',shirt: 'Lolo', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Francisco Punal Martínez',shirt: 'Patxi Punal', realteam: 'OSA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Francisco Andrés Silva Gajardo',shirt: 'Gato Silva', realteam: 'OSA', position: 'MED', nacionality: 'CHI',transferable: false)
Player.create(name: 'Raoul Cédric Loé',shirt: 'Loé', realteam: 'OSA', position: 'MED', nacionality: 'CAM',transferable: false)
Player.create(name: 'Miguel Ángel de las Cuevas Barberá',shirt: 'De las Cuevas', realteam: 'OSA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Cristian Lobato Villegas',shirt: 'Lobato', realteam: 'OSA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Sisinio González Martínez',shirt: 'Sisi', realteam: 'OSA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Roberto Torres Morales',shirt: 'Torres', realteam: 'OSA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Emiliano Daniel Armenteros',shirt: 'Armenteros', realteam: 'OSA', position: 'MED', nacionality: 'ARG',transferable: false)
Player.create(name: 'Álvaro Cejudo Carmona',shirt: 'Álvaro Cejudo', realteam: 'OSA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Juan Francisco Martínez Modesto',shirt: 'Nino', realteam: 'OSA', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Carlos Javier Acuna Caballero',shirt: 'Acuna', realteam: 'OSA', position: 'DEL', nacionality: 'PAR',transferable: false)
Player.create(name: 'Manuel Onwu Villafranca',shirt: 'Onwu', realteam: 'OSA', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Oriol Riera Magem',shirt: 'Oriol Riera', realteam: 'OSA', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Manuel Herrera Yagüe',shirt: 'Manu Herrera', realteam: 'ELX', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Antonio Rodríguez Martínez',shirt: 'Tono', realteam: 'ELX', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Alberto Tomás Botía Rabasco',shirt: 'Botía', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'David Rodríguez Lombán',shirt: 'Lombán', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Sergio Pelegrín López',shirt: 'Pelegrín', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Gregory Jose Henri Beranger',shirt: 'Beranger', realteam: 'ELX', position: 'DEF', nacionality: 'FRA',transferable: false)
Player.create(name: 'Eduardo Albacar Gallego',shirt: 'Edu Albacar', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Domingo Cisma González',shirt: 'Domingo Cisma', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Damián Nicolás Suárez Suárez',shirt: 'Damián Suárez', realteam: 'ELX', position: 'DEF', nacionality: 'URU',transferable: false)
Player.create(name: 'Ionut Cristian Sapunaru',shirt: 'Sapunaru', realteam: 'ELX', position: 'DEF', nacionality: 'RUM',transferable: false)
Player.create(name: 'Carlos Alberto Sánchez Moreno',shirt: 'Carlos Sánchez', realteam: 'ELX', position: 'MED', nacionality: 'COL',transferable: false)
Player.create(name: 'Alberto Rivera Pizarro',shirt: 'Rivera', realteam: 'ELX', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Rubén Salvador Pérez del Mármol',shirt: 'Rubén Pérez', realteam: 'ELX', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Sergio Martínez Mantecón',shirt: 'Mantecón', realteam: 'ELX', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Javier Márquez Moreno',shirt: 'Javi Márquez', realteam: 'ELX', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Aarón niguez Esclapez',shirt: 'Aarón', realteam: 'ELX', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Javier Flores Santacruz',shirt: 'Javi Flores', realteam: 'ELX', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Garry Mendes Rodrigues',shirt: 'Mendes', realteam: 'ELX', position: 'MED', nacionality: 'CVE',transferable: false)
Player.create(name: 'Fidel Chaves de la Torre',shirt: 'Fidel', realteam: 'ELX', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Manuel del Moral Fernández',shirt: 'Manu del Moral', realteam: 'ELX', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Ferrán Corominas Tellechea',shirt: 'Coro', realteam: 'ELX', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Richmond Yiadom Boakye',shirt: 'Boakye', realteam: 'ELX', position: 'DEL', nacionality: 'GHA',transferable: false)
Player.create(name: 'Carles Gil de Pareja Vicent',shirt: 'Carles Gil', realteam: 'ELX', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'David Cobeno Iglesias',shirt: 'Cobeno', realteam: 'RAY', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Rubén Iván Martínez Andrade',shirt: 'Rubén', realteam: 'RAY', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Alejandro Gálvez Jimena',shirt: 'Gálvez', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Leonel Ezequiel Galeano',shirt: 'Galeano', realteam: 'RAY', position: 'DEF', nacionality: 'ARG',transferable: false)
Player.create(name: 'José Eduardo Rosa Vale Castro',shirt: 'Źé Castro', realteam: 'RAY', position: 'DEF', nacionality: 'POR',transferable: false)
Player.create(name: 'Borja López Menéndez',shirt: 'Borja López', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'José Ignacio Martínez García',shirt: 'Nacho', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Razvan Dinca Rat',shirt: 'Rat', realteam: 'RAY', position: 'DEF', nacionality: 'RUM',transferable: false)
Player.create(name: 'Johan Andrés Mójica Palacio',shirt: 'Mójica', realteam: 'RAY', position: 'DEF', nacionality: 'COL',transferable: false)
Player.create(name: 'Roberto Román Triguero',shirt: 'Tito', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Anaitz Arbilla Zabala',shirt: 'Arbilla', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'José Raúl Baena Urdiales',shirt: 'Raúl Baena', realteam: 'RAY', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Adrián González Morales',shirt: 'Adrián González', realteam: 'RAY', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Roberto Trashorras Gayoso',shirt: 'Trashorras', realteam: 'RAY', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Saúl niguez Esclapez',shirt: 'Saúl', realteam: 'RAY', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Christian Alberto Cueva Bravo',shirt: 'Cueva', realteam: 'RAY', position: 'MED', nacionality: 'PER',transferable: false)
Player.create(name: 'José Carlos Fernández Vázquez',shirt: 'José Carlos', realteam: 'RAY', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Iago Falqué Silva',shirt: 'Iago Falqué', realteam: 'RAY', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jonathan Viera Ramos',shirt: 'Jonathan Viera', realteam: 'RAY', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Alhassane Bangoura',shirt: 'Lass', realteam: 'RAY', position: 'MED', nacionality: 'GUI',transferable: false)
Player.create(name: 'Nery Alberto Castillo Confalonieri',shirt: 'Nery Castillo', realteam: 'RAY', position: 'MED', nacionality: 'MEX',transferable: false)
Player.create(name: 'Alberto Perea Correoso',shirt: 'Alberto Perea', realteam: 'RAY', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Rubén Rochina Naixes',shirt: 'Rochina', realteam: 'RAY', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Alberto Bueno Calvo',shirt: 'Alberto Bueno', realteam: 'RAY', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Sebastián Bruno Fernández Miglierina',shirt: 'Seba Fernández', realteam: 'RAY', position: 'DEL', nacionality: 'URU',transferable: false)
Player.create(name: 'Samuele Longo',shirt: 'Longo', realteam: 'RAY', position: 'DEL', nacionality: 'ITA',transferable: false)
Player.create(name: 'Joaquín Óscar Larrivey',shirt: 'Larrivey', realteam: 'RAY', position: 'DEL', nacionality: 'ARG',transferable: false)
Player.create(name: 'Germán Parreno Boix',shirt: 'Parreno', realteam: 'ESP', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Francisco Casilla Cortés',shirt: 'Kiko Casilla', realteam: 'ESP', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Raúl Rodríguez Navarro',shirt: 'Raúl Rodríguez', realteam: 'ESP', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Sidnei Rechel da Silva Júnior',shirt: 'Sidnei', realteam: 'ESP', position: 'DEF', nacionality: 'BRA',transferable: false)
Player.create(name: 'Héctor Alfredo Moreno Herrera',shirt: 'Héctor Moreno', realteam: 'ESP', position: 'DEF', nacionality: 'MEX',transferable: false)
Player.create(name: 'Diego Daniel Colotto',shirt: 'Colotto', realteam: 'ESP', position: 'DEF', nacionality: 'ARG',transferable: false)
Player.create(name: 'Joan Capdevila Mendez',shirt: 'Capdevila', realteam: 'ESP', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Víctor Álvarez Delgado',shirt: 'Víctor Álvarez', realteam: 'ESP', position: 'DEF', nacionality: 'RUM',transferable: false)
Player.create(name: 'Juan Rafael Fuentes Hernández',shirt: 'Fuentes', realteam: 'ESP', position: 'DEF', nacionality: 'COL',transferable: false)
Player.create(name: 'Felipe Mattioni Rohde',shirt: 'Mattioni', realteam: 'ESP', position: 'DEF', nacionality: 'BRA',transferable: false)
Player.create(name: 'Javier López Rodríguez',shirt: 'Javi López', realteam: 'ESP', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'David López Silva',shirt: 'David López', realteam: 'ESP', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Víctor Sánchez Mata',shirt: 'Víctor Sánchez', realteam: 'ESP', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Alejandro Fernández Iglesias',shirt: 'Álex', realteam: 'ESP', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Abraham González Casanova',shirt: 'Abraham', realteam: 'ESP', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Simao Pedro Fonseca Sabrosa',shirt: 'Simao', realteam: 'ESP', position: 'MED', nacionality: 'POR',transferable: false)
Player.create(name: 'Gabriel Andrei Torje',shirt: 'Torje', realteam: 'ESP', position: 'MED', nacionality: 'RUM',transferable: false)
Player.create(name: 'Luis Miguel Afonso Fernandes',shirt: 'Pizzi', realteam: 'ESP', position: 'MED', nacionality: 'POR',transferable: false)
Player.create(name: 'Manuel Lanzarote Bruno',shirt: 'Lanzarote', realteam: 'ESP', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Sergio García de la Fuente',shirt: 'Sergio García', realteam: 'ESP', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Christian Ricardo Stuani Curbelo',shirt: 'Stuani', realteam: 'ESP', position: 'MED', nacionality: 'URU',transferable: false)
Player.create(name: 'Jhon Andrés Córdoba Copete',shirt: 'Córdoba', realteam: 'ESP', position: 'DEL', nacionality: 'COL',transferable: false)
Player.create(name: 'Sergio Álvarez Conde',shirt: 'Sergio Álvarez', realteam: 'CEL', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Yoel Rodríguez Oterino',shirt: 'Yoel', realteam: 'CEL', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Andreu Fontàs Prat',shirt: 'Fontàs', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Inigo López Montana',shirt: 'Inigo López', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Gustavo Daniel Cabral',shirt: 'Cabral', realteam: 'CEL', position: 'DEF', nacionality: 'ARG',transferable: false)
Player.create(name: 'David Costas Cordal',shirt: 'David Costas', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jon Aurtenetxe Borde',shirt: 'Aurtenetxe', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Antonio Rodríguez Dovale',shirt: 'Toni', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Hugo Mallo Novegil',shirt: 'Hugo Mallo', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jonathan Castro Otto',shirt: 'Otto', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Borja Oubina Meléndez',shirt: 'Borja Oubina', realteam: 'CEL', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Alejandro López Sánchez',shirt: 'Álex López', realteam: 'CEL', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Levy Clément Madinda',shirt: 'Madinda', realteam: 'CEL', position: 'MED', nacionality: 'GAB',transferable: false)
Player.create(name: 'Rafael Alcántara do Nascimento',shirt: 'Rafinha', realteam: 'CEL', position: 'MED', nacionality: 'BRA',transferable: false)
Player.create(name: 'Manuel Agudo Durán',shirt: 'Nolito', realteam: 'CEL', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Michael Krohn-Dehli',shirt: 'Krohn-Dehli', realteam: 'CEL', position: 'MED', nacionality: 'DIN',transferable: false)
Player.create(name: 'Fabián Ariel Orellana Valenzuela',shirt: 'Orellana', realteam: 'CEL', position: 'MED', nacionality: 'CHI',transferable: false)
Player.create(name: 'Augusto Matías Fernández',shirt: 'Augusto Fernández', realteam: 'CEL', position: 'MED', nacionality: 'ARG',transferable: false)
Player.create(name: 'Mario Bermejo Castanedo',shirt: 'Mario Bermejo', realteam: 'CEL', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Santiago Mina Lorenzo',shirt: 'Santi Mina', realteam: 'CEL', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Charles Dias de Oliveira',shirt: 'Charles', realteam: 'CEL', position: 'DEL', nacionality: 'BRA',transferable: false)
Player.create(name: 'Welliton Soares de Morais',shirt: 'Welliton', realteam: 'CEL', position: 'DEL', nacionality: 'BRA',transferable: false)
Player.create(name: 'Miguel Ángel Moyà Rumbo',shirt: 'Moyà', realteam: 'GET', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jordi Codina Rodríguez',shirt: 'Codina', realteam: 'GET', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Alexis Ruano Delgado',shirt: 'Alexis', realteam: 'GET', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Lisandro Ezequiel López',shirt: 'Lisandro López', realteam: 'GET', position: 'DEF', nacionality: 'ARG',transferable: false)
Player.create(name: 'Rafael López Gómez',shirt: 'Rafa', realteam: 'GET', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Roberto Lago Soto',shirt: 'Roberto Lago', realteam: 'GET', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Sergio Escudero Palomo',shirt: 'Escudero', realteam: 'GET', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Álvaro Arroyo Martínez',shirt: 'Arroyo', realteam: 'GET', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Juan Valera Espín',shirt: 'Juan Valera', realteam: 'GET', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Mehdi Lacen',shirt: 'Lacen', realteam: 'GET', position: 'MED', nacionality: 'ALG',transferable: false)
Player.create(name: 'Miguel Marcos Madera',shirt: 'Míchel', realteam: 'GET', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Juan Antonio Rodríguez Villamuela',shirt: 'Juan Rodríguez', realteam: 'GET', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Borja Fernández Fernández',shirt: 'Borja', realteam: 'GET', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Pedro Mosquera Parada',shirt: 'Mosquera', realteam: 'GET', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jaime Gavilán Martínez',shirt: 'Gavilán', realteam: 'GET', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Pablo Sarabia García',shirt: 'Sarabia', realteam: 'GET', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Jorge Sammir Cruz Campos',shirt: 'Sammir', realteam: 'GET', position: 'MED', nacionality: 'CRO',transferable: false)
Player.create(name: 'Diego Castro Giménez',shirt: 'Diego Castro', realteam: 'GET', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Ángel Lafita Castillo',shirt: 'Lafita', realteam: 'GET', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Pedro León Sánchez Gil',shirt: 'Pedro León', realteam: 'GET', position: ',MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Ciprian Andrei Marica',shirt: 'Ciprian', realteam: 'GET', position: 'DEL', nacionality: 'RUM',transferable: false)
Player.create(name: 'Adrián Colunga Pérez',shirt: 'Adrián Colunga', realteam: 'GET', position: 'DEL', nacionality: 'ESP',transferable: false)
Player.create(name: 'Orestis Karnezis',shirt: 'Karnezis', realteam: 'GRA', position: 'POR', nacionality: 'GRE',transferable: false)
Player.create(name: 'Roberto Fernández Alvalleros',shirt: 'Roberto', realteam: 'GRA', position: 'POR', nacionality: 'ESP',transferable: false)
Player.create(name: 'Diego Mainz García',shirt: 'Diego Mainz', realteam: 'GRA', position: 'DEF', nacionality: 'ESP',transferable: false)
Player.create(name: 'Tiago Abiola Defim Almeida Ilori',shirt: 'Tiago Ilori', realteam: 'GRA', position: 'DEF', nacionality: 'POR',transferable: false)
Player.create(name: 'Alexandre Coeff',shirt: 'Coeff', realteam: 'GRA', position: 'GRA', nacionality: 'FRA',transferable: false)
Player.create(name: 'Jeison Fabián Murillo Cerón',shirt: 'Murillo', realteam: 'GRA', position: 'DEF', nacionality: 'COL',transferable: false)
Player.create(name: 'Brayan Alexis Angulo León',shirt: 'Brayan Angulo', realteam: 'GRA', position: 'DEF', nacionality: 'COL',transferable: false)
Player.create(name: 'Allan-Romeo Nyom',shirt: 'Nyom', realteam: 'GRA', position: 'DEF', nacionality: 'CAM',transferable: false)
Player.create(name: 'Dimitri Foulquier',shirt: 'Foulquier', realteam: 'GRA', position: 'MED', nacionality: 'FRA',transferable: false)
Player.create(name: 'Manuel Rolando Iturra Urrutia',shirt: 'Iturra', realteam: 'GRA', position: 'MED', nacionality: 'CHI',transferable: false)
Player.create(name: 'Francisco Rico Castano',shirt: 'Fran Rico', realteam: 'GRA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'José Luis García del Pozo',shirt: 'Recio', realteam: 'GRA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Daniel González Benítez',shirt: 'Dani Benítez', realteam: 'GRA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Yacine Brahimi',shirt: 'Brahimi', realteam: 'GRA', position: 'MED', nacionality: 'ALG',transferable: false)
Player.create(name: 'Diego Mario Buonanotte Rende',shirt: 'Buonanotte', realteam: 'GRA', position: 'MED', nacionality: 'ARG',transferable: false)
Player.create(name: 'Francisco Medina Luna',shirt: 'Piti', realteam: 'GRA', position: 'MED', nacionality: 'ESP',transferable: false)
Player.create(name: 'Michael Pereira',shirt: 'Pereira', realteam: 'GRA', position: 'MED', nacionality: 'FRA',transferable: false)
Player.create(name: 'Odion Jude Ighalo',shirt: 'Ighalo', realteam: 'GRA', position: 'DEL', nacionality: 'NIG',transferable: false)
Player.create(name: 'Youssef El-Arabi',shirt: 'El Arabi', realteam: 'GRA', position: 'DEL', nacionality: 'MAR',transferable: false)
Player.create(name: 'Iván Sánchez-Rico Soto',shirt: 'Riki', realteam: 'GRA', position: 'DEL', nacionality: 'ESP',transferable: false)