#encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Player.create(name: 'Esteban Andrés Suárez',shirt: 'Esteban', realteam: 'ALM', position: 'POR', nacionality: 'ESP',value: 100000)
Player.create(name: 'Julián Cuesta Díaz',shirt: 'Julián', realteam: 'ALM', position: 'POR', nacionality: 'ESP',value: 300000)
Player.create(name: 'Marco Natanael Torsiglieri',shirt: 'Torsiglieri', realteam: 'ALM', position: 'DEF', nacionality: 'ARG',value: 3000000)
Player.create(name: 'Marcelo Andŕes Silva Fernández',shirt: 'Marcelo Silva', realteam: 'ALM', position: 'DEF', nacionality: 'URU',value: 600000)
Player.create(name: 'Hans Aléxis Martínez Cabrera',shirt: 'Hans Martínez', realteam: 'ALM', position: 'DEF', nacionality: 'CHI',value: 800000)
Player.create(name: 'Ángel Trujillo Canorea',shirt: 'Trujillo', realteam: 'ALM', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Sebastián Dubarbier',shirt: 'Dubarbier', realteam: 'ALM', position: 'DEF', nacionality: 'ARG',value: 1500000)
Player.create(name: 'José Manuel Jiménez Ortiz',shirt: 'Mané', realteam: 'ALM', position: 'DEF', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Rafael Ramos Lozano',shirt: 'Rafita', realteam: 'ALM', position: 'DEF', nacionality: 'ESP',value: 800000)
Player.create(name: 'Nelson Augusto Tomar Ramos',shirt: 'Nelson', realteam: 'ALM', position: 'DEF', nacionality: 'POR',value: 1200000)
Player.create(name: 'Marcos Tébar Ramiro',shirt: 'Marcos Tébar', realteam: 'ALM', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'José Antonio García Rabasco',shirt: 'Verza', realteam: 'ALM', position: 'MED', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Ramon Olamilekan Azeez',shirt: 'Azeez', realteam: 'ALM', position: 'MED', nacionality: 'NIG',value: 2000000)
Player.create(name: 'Miguel Ángel García Pérez-Roldán',shirt: 'Corona', realteam: 'ALM', position: 'MED', nacionality: 'ESP',value: 800000)
Player.create(name: 'Fernando Soriano Marcos',shirt: 'Soriano', realteam: 'ALM', position: 'MED', nacionality: 'ESP',value: 400000)
Player.create(name: 'Aleix Vidal Parreu',shirt: 'Aleix Vidal', realteam: 'ALM', position: 'MED', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Hélder Jorge Leal Rodrigues Barbosa',shirt: 'Hélder Barbosa', realteam: 'ALM', position: 'MED', nacionality: 'POR',value: 2000000)
Player.create(name: 'Jesús Joaquín Fernández Sáez de la Torre',shirt: 'Suso', realteam: 'ALM', position: 'MED', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Jonathan Sundy Zongo',shirt: 'Zongo', realteam: 'ALM', position: 'MED', nacionality: 'BUR',value: 600000)
Player.create(name: 'Óscar Díaz González',shirt: 'Óscar Díaz', realteam: 'ALM', position: 'DEL', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Rodrigo Ríos Lozano',shirt: 'Rodri', realteam: 'ALM', position: 'DEL', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Jaime Jiménez Merlo',shirt: 'Jaime Jiménez', realteam: 'VAD', position: 'POR', nacionality: 'ESP',value: 600000)
Player.create(name: 'Diego Marino Villar',shirt: 'Marino', realteam: 'VAD', position: 'POR', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Heinz Bartmettler',shirt: 'Bartmettler', realteam: 'VAD', position: 'DEF', nacionality: 'DOM',value: 500000)
Player.create(name: 'Marc Valiente Hernández',shirt: 'Valiente', realteam: 'VAD', position: 'DEF', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Jesús Rueda Ambrosio',shirt: 'Rueda', realteam: 'VAD', position: 'DEF', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Stefan Mitrovic',shirt: 'Mitrovic', realteam: 'VAD', position: 'DEF', nacionality: 'SER',value: 1000000)
Player.create(name: 'Carlos González Pena',shirt: 'Pena', realteam: 'VAD', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Zakaria Bergdich',shirt: 'Bergdich', realteam: 'VAD', position: 'DEF', nacionality: 'MAR',value: 1000000)
Player.create(name: 'Antonio Rukavina',shirt: 'Rukavina', realteam: 'VAD', position: 'DEF', nacionality: 'SER',value: 4000000)
Player.create(name: 'Gilberto García Olarte',shirt: 'Alcatraz', realteam: 'VAD', position: 'DEF', nacionality: 'COL',value: 800000)
Player.create(name: 'Javier Baraja Vegas',shirt: 'Baraja', realteam: 'VAD', position: 'DEF', nacionality: 'ESP',value: 400000)
Player.create(name: 'Lluis Sastre Reus',shirt: 'Sastre', realteam: 'VAD', position: 'MED', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Álvaro Rubio Robles',shirt: 'Álvaro Rubio', realteam: 'VAD', position: 'MED', nacionality: 'ESP',value: 200000)
Player.create(name: 'Víctor Pérez Alonso',shirt: 'Víctor Pérez', realteam: 'VAD', position: 'MED', nacionality: 'ESP',value: 1800000)
Player.create(name: 'Fausto Rossi',shirt: 'Rossi', realteam: 'VAD', position: 'MED', nacionality: 'ITA',value: 2000000)
Player.create(name: 'Óscar Javier González Marcos',shirt: 'Óscar', realteam: 'VAD', position: 'MED', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Julián Omar Ramos Suárez',shirt: 'Omar', realteam: 'VAD', position: 'MED', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Valdet Rama',shirt: 'Rama', realteam: 'VAD', position: 'MED', nacionality: 'ALB',value: 1000000)
Player.create(name: 'Daniel Larsson',shirt: 'Larsson', realteam: 'VAD', position: 'DEL', nacionality: 'SUE',value: 1200000)
Player.create(name: 'Jeffrén Suárez Bermúdez',shirt: 'Jeffrén', realteam: 'VAD', position: 'DEL', nacionality: 'VEN',value: 2500000)
Player.create(name: 'Humberto Segundo Osorio Botello',shirt: 'Osorio', realteam: 'VAD', position: 'DEL', nacionality: 'COL',value: 1200000)
Player.create(name: 'Javier Guerra Rodríguez',shirt: 'Javi Guerra', realteam: 'VAD', position: 'DEL', nacionality: 'ESP',value: 3500000)
Player.create(name: 'Mateus Alberto Contreiras Gonçalves',shirt: 'Manucho', realteam: 'VAD', position: 'DEL', nacionality: 'ANG',value: 1500000)
Player.create(name: 'Keylor Antonio Navas Gamboa',shirt: 'Keylor Navas', realteam: 'LEV', position: 'POR', nacionality: 'CRI',value: 4000000)
Player.create(name: 'Javier Jiménez Camarero',shirt: 'Javi Jiménez', realteam: 'LEV', position: 'POR', nacionality: 'ESP',value: 1200000)
Player.create(name: 'David Navarro Pedrós',shirt: 'David Navarro', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',value: 400000)
Player.create(name: 'Héctor Rodás Ramírez',shirt: 'Héctor Rodás', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',value: 600000)
Player.create(name: 'Loukas Vyntra',shirt: 'Vyntra', realteam: 'LEV', position: 'DEF', nacionality: 'GRE',value: 1000000)
Player.create(name: 'Issam El-Adoua',shirt: 'El Adoua', realteam: 'LEV', position: 'DEF', nacionality: 'MAR',value: 1500000)
Player.create(name: 'Juan Francisco García García',shirt: 'Juanfran', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',value: 100000)
Player.create(name: 'Nikolaos Karabelas',shirt: 'Karabelas', realteam: 'LEV', position: 'DEF', nacionality: 'GRE',value: 500000)
Player.create(name: 'Pedro López Múnoz',shirt: 'Pedro López', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Alberto Gómez Fernández',shirt: 'Nagore', realteam: 'LEV', position: 'DEF', nacionality: 'ESP',value: 300000)
Player.create(name: 'Miguel Pallardó González',shirt: 'Pallardó', realteam: 'LEV', position: 'MED', nacionality: 'ESP',value: 500000)
Player.create(name: 'Sergio da Silva Pinto',shirt: 'Sergio Pinto', realteam: 'LEV', position: 'MED', nacionality: 'POR',value: 1000000)
Player.create(name: 'Mohammed Lamine Sissoko',shirt: 'Sissoko', realteam: 'LEV', position: 'MED', nacionality: 'MAL',value: 2000000)
Player.create(name: 'Papakouli Diop',shirt: 'Papakouli Diop', realteam: 'LEV', position: 'MED', nacionality: 'SEN',value: 3500000)
Player.create(name: 'Simao Mate Junior',shirt: 'Simao', realteam: 'LEV', position: 'MED', nacionality: 'MOZ',value: 1500000)
Player.create(name: 'Jordi Xumetra Feliu',shirt: 'Xumetra', realteam: 'LEV', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Pedro Ríos Maestre',shirt: 'Pedro Ríos', realteam: 'LEV', position: 'MED', nacionality: 'ESP',value: 900000)
Player.create(name: 'Andreas Ivanschitz',shirt: 'Ivanschitz', realteam: 'LEV', position: 'MED', nacionality: 'AUT',value: 3000000)
Player.create(name: 'Rubén García Santos',shirt: 'Rubén', realteam: 'LEV', position: 'DEL', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Nabil El-Zhar',shirt: 'El Zhar', realteam: 'LEV', position: 'DEL', nacionality: 'MAR',value: 2000000)
Player.create(name: 'Víctor Casadesús Castano',shirt: 'Víctor Casadesús', realteam: 'LEV', position: 'DEL', nacionality: 'ESP',value: 2500000)
Player.create(name: 'David Barral Torres',shirt: 'David Barral', realteam: 'LEV', position: 'DEL', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Ángel Luis Rodríguez Díaz',shirt: 'Ángel', realteam: 'LEV', position: 'DEL', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Papa Babacar Diawara',shirt: 'Babá', realteam: 'LEV', position: 'DEL', nacionality: 'SEN',value: 1800000)
Player.create(name: 'Asier Riesgo Unamuno',shirt: 'Riesgo', realteam: 'OSA', position: 'POR', nacionality: 'ESP',value: 500000)
Player.create(name: 'Andrés Fernández Moreno',shirt: 'Andrés Fernández', realteam: 'OSA', position: 'POR', nacionality: 'ESP',value: 3500000)
Player.create(name: 'Miguel Flano Bezunartea',shirt: 'Flano', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Alejandro Arribas Garrido',shirt: 'Arribas', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Jordan Lotiès',shirt: 'Lotiès', realteam: 'OSA', position: 'DEF', nacionality: 'FRA',value: 3000000)
Player.create(name: 'Joan Oriol Gracia',shirt: 'Oriol', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Eneko Satrústegui Plano',shirt: 'Satrústegui', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',value: 300000)
Player.create(name: 'Marc Bertrán Vilanova',shirt: 'Bertrán', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Oier Sanjurjo Maté',shirt: 'Oier', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',value: 1800000)
Player.create(name: 'Damià Abella Páez',shirt: 'Damià', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Manuel Ortiz Toribio',shirt: 'Lolo', realteam: 'OSA', position: 'DEF', nacionality: 'ESP',value: 1800000)
Player.create(name: 'Francisco Punal Martínez',shirt: 'Patxi Punal', realteam: 'OSA', position: 'MED', nacionality: 'ESP',value: 100000)
Player.create(name: 'Francisco Andrés Silva Gajardo',shirt: 'Gato Silva', realteam: 'OSA', position: 'MED', nacionality: 'CHI',value: 2000000)
Player.create(name: 'Raoul Cédric Loé',shirt: 'Loé', realteam: 'OSA', position: 'MED', nacionality: 'CAM',value: 1800000)
Player.create(name: 'Miguel Ángel de las Cuevas Barberá',shirt: 'De las Cuevas', realteam: 'OSA', position: 'MED', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Cristian Lobato Villegas',shirt: 'Lobato', realteam: 'OSA', position: 'MED', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Sisinio González Martínez',shirt: 'Sisi', realteam: 'OSA', position: 'MED', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Roberto Torres Morales',shirt: 'Torres', realteam: 'OSA', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Emiliano Daniel Armenteros',shirt: 'Armenteros', realteam: 'OSA', position: 'MED', nacionality: 'ARG',value: 2500000)
Player.create(name: 'Álvaro Cejudo Carmona',shirt: 'Álvaro Cejudo', realteam: 'OSA', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Juan Francisco Martínez Modesto',shirt: 'Nino', realteam: 'OSA', position: 'DEL', nacionality: 'ESP',value: 600000)
Player.create(name: 'Carlos Javier Acuna Caballero',shirt: 'Acuna', realteam: 'OSA', position: 'DEL', nacionality: 'PAR',value: 700000)
Player.create(name: 'Manuel Onwu Villafranca',shirt: 'Onwu', realteam: 'OSA', position: 'DEL', nacionality: 'ESP',value: 800000)
Player.create(name: 'Oriol Riera Magem',shirt: 'Oriol Riera', realteam: 'OSA', position: 'DEL', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Manuel Herrera Yagüe',shirt: 'Manu Herrera', realteam: 'ELX', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Antonio Rodríguez Martínez',shirt: 'Tono', realteam: 'ELX', position: 'MED', nacionality: 'ESP',value: 900000)
Player.create(name: 'Alberto Tomás Botía Rabasco',shirt: 'Botía', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',value: 5000000)
Player.create(name: 'David Rodríguez Lombán',shirt: 'Lombán', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Sergio Pelegrín López',shirt: 'Pelegrín', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',value: 300000)
Player.create(name: 'Gregory Jose Henri Beranger',shirt: 'Beranger', realteam: 'ELX', position: 'DEF', nacionality: 'FRA',value: 100000)
Player.create(name: 'Eduardo Albacar Gallego',shirt: 'Edu Albacar', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Domingo Cisma González',shirt: 'Domingo Cisma', realteam: 'ELX', position: 'DEF', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Damián Nicolás Suárez Suárez',shirt: 'Damián Suárez', realteam: 'ELX', position: 'DEF', nacionality: 'URU',value: 3000000)
Player.create(name: 'Ionut Cristian Sapunaru',shirt: 'Sapunaru', realteam: 'ELX', position: 'DEF', nacionality: 'RUM',value: 1000000)
Player.create(name: 'Carlos Alberto Sánchez Moreno',shirt: 'Carlos Sánchez', realteam: 'ELX', position: 'MED', nacionality: 'COL',value: 2500000)
Player.create(name: 'Alberto Rivera Pizarro',shirt: 'Rivera', realteam: 'ELX', position: 'MED', nacionality: 'ESP',value: 200000)
Player.create(name: 'Rubén Salvador Pérez del Mármol',shirt: 'Rubén Pérez', realteam: 'ELX', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Sergio Martínez Mantecón',shirt: 'Mantecón', realteam: 'ELX', position: 'MED', nacionality: 'ESP',value: 600000)
Player.create(name: 'Javier Márquez Moreno',shirt: 'Javi Márquez', realteam: 'ELX', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Aarón niguez Esclapez',shirt: 'Aarón', realteam: 'ELX', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Javier Flores Santacruz',shirt: 'Javi Flores', realteam: 'ELX', position: 'MED', nacionality: 'ESP',value: 300000)
Player.create(name: 'Garry Mendes Rodrigues',shirt: 'Mendes', realteam: 'ELX', position: 'MED', nacionality: 'CVE',value: 2000000)
Player.create(name: 'Fidel Chaves de la Torre',shirt: 'Fidel', realteam: 'ELX', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Manuel del Moral Fernández',shirt: 'Manu del Moral', realteam: 'ELX', position: 'DEL', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Ferrán Corominas Tellechea',shirt: 'Coro', realteam: 'ELX', position: 'DEL', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Richmond Yiadom Boakye',shirt: 'Boakye', realteam: 'ELX', position: 'DEL', nacionality: 'GHA',value: 3000000)
Player.create(name: 'Carles Gil de Pareja Vicent',shirt: 'Carles Gil', realteam: 'ELX', position: 'DEL', nacionality: 'ESP',value: 3000000)
Player.create(name: 'David Cobeno Iglesias',shirt: 'Cobeno', realteam: 'RAY', position: 'POR', nacionality: 'ESP',value: 600000)
Player.create(name: 'Rubén Iván Martínez Andrade',shirt: 'Rubén', realteam: 'RAY', position: 'POR', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Alejandro Gálvez Jimena',shirt: 'Gálvez', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Leonel Ezequiel Galeano',shirt: 'Galeano', realteam: 'RAY', position: 'DEF', nacionality: 'ARG',value: 800000)
Player.create(name: 'José Eduardo Rosa Vale Castro',shirt: 'Źé Castro', realteam: 'RAY', position: 'DEF', nacionality: 'POR',value: 900000)
Player.create(name: 'Borja López Menéndez',shirt: 'Borja López', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'José Ignacio Martínez García',shirt: 'Nacho', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Razvan Dinca Rat',shirt: 'Rat', realteam: 'RAY', position: 'DEF', nacionality: 'RUM',value: 1500000)
Player.create(name: 'Johan Andrés Mójica Palacio',shirt: 'Mójica', realteam: 'RAY', position: 'DEF', nacionality: 'COL',value: 500000)
Player.create(name: 'Roberto Román Triguero',shirt: 'Tito', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Anaitz Arbilla Zabala',shirt: 'Arbilla', realteam: 'RAY', position: 'DEF', nacionality: 'ESP',value: 1000000)
Player.create(name: 'José Raúl Baena Urdiales',shirt: 'Raúl Baena', realteam: 'RAY', position: 'MED', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Adrián González Morales',shirt: 'Adrián González', realteam: 'RAY', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Roberto Trashorras Gayoso',shirt: 'Trashorras', realteam: 'RAY', position: 'MED', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Saúl niguez Esclapez',shirt: 'Saúl', realteam: 'RAY', position: 'MED', nacionality: 'ESP',value: 7500000)
Player.create(name: 'Christian Alberto Cueva Bravo',shirt: 'Cueva', realteam: 'RAY', position: 'MED', nacionality: 'PER',value: 800000)
Player.create(name: 'José Carlos Fernández Vázquez',shirt: 'José Carlos', realteam: 'RAY', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Iago Falqué Silva',shirt: 'Iago Falqué', realteam: 'RAY', position: 'MED', nacionality: 'ESP',value: 1800000)
Player.create(name: 'Jonathan Viera Ramos',shirt: 'Jonathan Viera', realteam: 'RAY', position: 'MED', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Alhassane Bangoura',shirt: 'Lass', realteam: 'RAY', position: 'MED', nacionality: 'GUI',value: 2500000)
Player.create(name: 'Nery Alberto Castillo Confalonieri',shirt: 'Nery Castillo', realteam: 'RAY', position: 'MED', nacionality: 'MEX',value: 1000000)
Player.create(name: 'Alberto Perea Correoso',shirt: 'Alberto Perea', realteam: 'RAY', position: 'DEL', nacionality: 'ESP',value: 300000)
Player.create(name: 'Rubén Rochina Naixes',shirt: 'Rochina', realteam: 'RAY', position: 'DEL', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Alberto Bueno Calvo',shirt: 'Alberto Bueno', realteam: 'RAY', position: 'DEL', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Sebastián Bruno Fernández Miglierina',shirt: 'Seba Fernández', realteam: 'RAY', position: 'DEL', nacionality: 'URU',value: 1500000)
Player.create(name: 'Samuele Longo',shirt: 'Longo', realteam: 'RAY', position: 'DEL', nacionality: 'ITA',value: 2000000)
Player.create(name: 'Joaquín Óscar Larrivey',shirt: 'Larrivey', realteam: 'RAY', position: 'DEL', nacionality: 'ARG',value: 1000000)
Player.create(name: 'Germán Parreño Boix',shirt: 'Parreño', realteam: 'ESP', position: 'POR', nacionality: 'ESP',value: 200000)
Player.create(name: 'Francisco Casilla Cortés',shirt: 'Kiko Casilla', realteam: 'ESP', position: 'POR', nacionality: 'ESP',value: 3500000)
Player.create(name: 'Raúl Rodríguez Navarro',shirt: 'Raúl Rodríguez', realteam: 'ESP', position: 'DEF', nacionality: 'ESP',value: 1800000)
Player.create(name: 'Sidnei Rechel da Silva Júnior',shirt: 'Sidnei', realteam: 'ESP', position: 'DEF', nacionality: 'BRA',value: 1500000)
Player.create(name: 'Héctor Alfredo Moreno Herrera',shirt: 'Héctor Moreno', realteam: 'ESP', position: 'DEF', nacionality: 'MEX',value: 7000000)
Player.create(name: 'Diego Daniel Colotto',shirt: 'Colotto', realteam: 'ESP', position: 'DEF', nacionality: 'ARG',value: 1800000)
Player.create(name: 'Joan Capdevila Mendez',shirt: 'Capdevila', realteam: 'ESP', position: 'DEF', nacionality: 'ESP',value: 200000)
Player.create(name: 'Víctor Álvarez Delgado',shirt: 'Víctor Álvarez', realteam: 'ESP', position: 'DEF', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Juan Rafael Fuentes Hernández',shirt: 'Fuentes', realteam: 'ESP', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Felipe Mattioni Rohde',shirt: 'Mattioni', realteam: 'ESP', position: 'DEF', nacionality: 'BRA',value: 1000000)
Player.create(name: 'Javier López Rodríguez',shirt: 'Javi López', realteam: 'ESP', position: 'DEF', nacionality: 'ESP',value: 3000000)
Player.create(name: 'David López Silva',shirt: 'David López', realteam: 'ESP', position: 'MED', nacionality: 'ESP',value: 1800000)
Player.create(name: 'Víctor Sánchez Mata',shirt: 'Víctor Sánchez', realteam: 'ESP', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Alejandro Fernández Iglesias',shirt: 'Álex', realteam: 'ESP', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Abraham González Casanova',shirt: 'Abraham', realteam: 'ESP', position: 'MED', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Simao Pedro Fonseca Sabrosa',shirt: 'Simao', realteam: 'ESP', position: 'MED', nacionality: 'POR',value: 1500000)
Player.create(name: 'Gabriel Andrei Torje',shirt: 'Torje', realteam: 'ESP', position: 'MED', nacionality: 'RUM',value: 3000000)
Player.create(name: 'Luis Miguel Afonso Fernandes',shirt: 'Pizzi', realteam: 'ESP', position: 'MED', nacionality: 'POR',value: 3000000)
Player.create(name: 'Manuel Lanzarote Bruno',shirt: 'Lanzarote', realteam: 'ESP', position: 'DEL', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Sergio García de la Fuente',shirt: 'Sergio García', realteam: 'ESP', position: 'MED', nacionality: 'ESP',value: 3500000)
Player.create(name: 'Christian Ricardo Stuani Curbelo',shirt: 'Stuani', realteam: 'ESP', position: 'MED', nacionality: 'URU',value: 3000000)
Player.create(name: 'Jhon Andrés Córdoba Copete',shirt: 'Córdoba', realteam: 'ESP', position: 'DEL', nacionality: 'COL',value: 1000000)
Player.create(name: 'Sergio Álvarez Conde',shirt: 'Sergio Álvarez', realteam: 'CEL', position: 'POR', nacionality: 'ESP',value: 500000)
Player.create(name: 'Yoel Rodríguez Oterino',shirt: 'Yoel', realteam: 'CEL', position: 'POR', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Andreu Fontàs Prat',shirt: 'Fontàs', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Inigo López Montana',shirt: 'Inigo López', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Gustavo Daniel Cabral',shirt: 'Cabral', realteam: 'CEL', position: 'DEF', nacionality: 'ARG',value: 1200000)
Player.create(name: 'David Costas Cordal',shirt: 'David Costas', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Jon Aurtenetxe Borde',shirt: 'Aurtenetxe', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Antonio Rodríguez Dovale',shirt: 'Toni', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',value: 900000)
Player.create(name: 'Hugo Mallo Novegil',shirt: 'Hugo Mallo', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',value: 300000)
Player.create(name: 'Jonathan Castro Otto',shirt: 'Otto', realteam: 'CEL', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Borja Oubina Meléndez',shirt: 'Borja Oubina', realteam: 'CEL', position: 'MED', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Alejandro López Sánchez',shirt: 'Álex López', realteam: 'CEL', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Levy Clément Madinda',shirt: 'Madinda', realteam: 'CEL', position: 'MED', nacionality: 'GAB',value: 300000)
Player.create(name: 'Rafael Alcántara do Nascimento',shirt: 'Rafinha', realteam: 'CEL', position: 'MED', nacionality: 'BRA',value: 7500000)
Player.create(name: 'Manuel Agudo Durán',shirt: 'Nolito', realteam: 'CEL', position: 'MED', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Michael Krohn-Dehli',shirt: 'Krohn-Dehli', realteam: 'CEL', position: 'MED', nacionality: 'DIN',value: 2500000)
Player.create(name: 'Fabián Ariel Orellana Valenzuela',shirt: 'Orellana', realteam: 'CEL', position: 'MED', nacionality: 'CHI',value: 2500000)
Player.create(name: 'Augusto Matías Fernández',shirt: 'Augusto Fernández', realteam: 'CEL', position: 'MED', nacionality: 'ARG',value: 4000000)
Player.create(name: 'Mario Bermejo Castanedo',shirt: 'Mario Bermejo', realteam: 'CEL', position: 'DEL', nacionality: 'ESP',value: 200000)
Player.create(name: 'Santiago Mina Lorenzo',shirt: 'Santi Mina', realteam: 'CEL', position: 'DEL', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Charles Dias de Oliveira',shirt: 'Charles', realteam: 'CEL', position: 'DEL', nacionality: 'BRA',value: 2500000)
Player.create(name: 'Welliton Soares de Morais',shirt: 'Welliton', realteam: 'CEL', position: 'DEL', nacionality: 'BRA',value: 2500000)
Player.create(name: 'Miguel Ángel Moyà Rumbo',shirt: 'Moyà', realteam: 'GET', position: 'POR', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Jordi Codina Rodríguez',shirt: 'Codina', realteam: 'GET', position: 'POR', nacionality: 'ESP',value: 800000)
Player.create(name: 'Alexis Ruano Delgado',shirt: 'Alexis', realteam: 'GET', position: 'DEF', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Lisandro Ezequiel López',shirt: 'Lisandro López', realteam: 'GET', position: 'DEF', nacionality: 'ARG',value: 6000000)
Player.create(name: 'Rafael López Gómez',shirt: 'Rafa', realteam: 'GET', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Roberto Lago Soto',shirt: 'Roberto Lago', realteam: 'GET', position: 'DEF', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Sergio Escudero Palomo',shirt: 'Escudero', realteam: 'GET', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Álvaro Arroyo Martínez',shirt: 'Arroyo', realteam: 'GET', position: 'DEF', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Juan Valera Espín',shirt: 'Juan Valera', realteam: 'GET', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Mehdi Lacen',shirt: 'Lacen', realteam: 'GET', position: 'MED', nacionality: 'ALG',value: 1500000)
Player.create(name: 'Miguel Marcos Madera',shirt: 'Míchel', realteam: 'GET', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Juan Antonio Rodríguez Villamuela',shirt: 'Juan Rodríguez', realteam: 'GET', position: 'MED', nacionality: 'ESP',value: 600000)
Player.create(name: 'Borja Fernández Fernández',shirt: 'Borja', realteam: 'GET', position: 'MED', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Pedro Mosquera Parada',shirt: 'Mosquera', realteam: 'GET', position: 'MED', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Jaime Gavilán Martínez',shirt: 'Gavilán', realteam: 'GET', position: 'MED', nacionality: 'ESP',value: 1600000)
Player.create(name: 'Pablo Sarabia García',shirt: 'Sarabia', realteam: 'GET', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Jorge Sammir Cruz Campos',shirt: 'Sammir', realteam: 'GET', position: 'MED', nacionality: 'CRO',value: 3000000)
Player.create(name: 'Diego Castro Giménez',shirt: 'Diego Castro', realteam: 'GET', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Ángel Lafita Castillo',shirt: 'Lafita', realteam: 'GET', position: 'MED', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Pedro León Sánchez Gil',shirt: 'Pedro León', realteam: 'GET', position: ',MED', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Ciprian Andrei Marica',shirt: 'Ciprian', realteam: 'GET', position: 'DEL', nacionality: 'RUM',value: 1500000)
Player.create(name: 'Adrián Colunga Pérez',shirt: 'Adrián Colunga', realteam: 'GET', position: 'DEL', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Orestis Karnezis',shirt: 'Karnezis', realteam: 'GRA', position: 'POR', nacionality: 'GRE',value: 1500000)
Player.create(name: 'Roberto Fernández Alvalleros',shirt: 'Roberto', realteam: 'GRA', position: 'POR', nacionality: 'ESP',value: 600000)
Player.create(name: 'Diego Mainz García',shirt: 'Diego Mainz', realteam: 'GRA', position: 'DEF', nacionality: 'ESP',value: 1800000)
Player.create(name: 'Tiago Abiola Defim Almeida Ilori',shirt: 'Tiago Ilori', realteam: 'GRA', position: 'DEF', nacionality: 'POR',value: 4000000)
Player.create(name: 'Alexandre Coeff',shirt: 'Coeff', realteam: 'GRA', position: 'GRA', nacionality: 'FRA',value: 800000)
Player.create(name: 'Jeison Fabián Murillo Cerón',shirt: 'Murillo', realteam: 'GRA', position: 'DEF', nacionality: 'COL',value: 4000000)
Player.create(name: 'Brayan Alexis Angulo León',shirt: 'Brayan Angulo', realteam: 'GRA', position: 'DEF', nacionality: 'COL',value: 1500000)
Player.create(name: 'Allan-Romeo Nyom',shirt: 'Nyom', realteam: 'GRA', position: 'DEF', nacionality: 'CAM',value: 5000000)
Player.create(name: 'Dimitri Foulquier',shirt: 'Foulquier', realteam: 'GRA', position: 'MED', nacionality: 'FRA',value: 1500000)
Player.create(name: 'Manuel Rolando Iturra Urrutia',shirt: 'Iturra', realteam: 'GRA', position: 'MED', nacionality: 'CHI',value: 3500000)
Player.create(name: 'Francisco Rico Castano',shirt: 'Fran Rico', realteam: 'GRA', position: 'MED', nacionality: 'ESP',value: 1800000)
Player.create(name: 'José Luis García del Pozo',shirt: 'Recio', realteam: 'GRA', position: 'MED', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Daniel González Benítez',shirt: 'Dani Benítez', realteam: 'GRA', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Yacine Brahimi',shirt: 'Brahimi', realteam: 'GRA', position: 'MED', nacionality: 'ALG',value: 4000000)
Player.create(name: 'Diego Mario Buonanotte Rende',shirt: 'Buonanotte', realteam: 'GRA', position: 'MED', nacionality: 'ARG',value: 1500000)
Player.create(name: 'Francisco Medina Luna',shirt: 'Piti', realteam: 'GRA', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Michael Pereira',shirt: 'Pereira', realteam: 'GRA', position: 'MED', nacionality: 'FRA',value: 2000000)
Player.create(name: 'Odion Jude Ighalo',shirt: 'Ighalo', realteam: 'GRA', position: 'DEL', nacionality: 'NIG',value: 2500000)
Player.create(name: 'Youssef El-Arabi',shirt: 'El Arabi', realteam: 'GRA', position: 'DEL', nacionality: 'MAR',value: 6500000)
Player.create(name: 'Iván Sánchez-Rico Soto',shirt: 'Riki', realteam: 'GRA', position: 'DEL', nacionality: 'ESP',value: 1800000)
Player.create(name: 'Antonio Adán Garrido',shirt:'Adán', realteam: 'BET', position: 'POR', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Guillermo Sara',shirt: 'Sara', realteam: 'BET', position: 'POR', nacionality: 'ARG',value: 1000000)
Player.create(name: 'Paulo Afonso Santos Júnior',shirt: 'Paulao', realteam: 'BET', position: 'DEF', nacionality: 'POR',value: 1500000)
Player.create(name: 'Antonio Amaya Carazo',shirt: 'Amaya', realteam: 'BET', position: 'DEF', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Damien Perquis',shirt: 'Perquis', realteam: 'BET', position: 'GRA', nacionality: 'FRA',value: 1200000)
Player.create(name: 'Jordi Figueras Montel',shirt: 'Jordi Figueras', realteam: 'BET', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Dídac Vilà Rosselló',shirt: 'Didac Vilà', realteam: 'BET', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Ignacio Pérez Santamaría',shirt: 'Nacho', realteam: 'BET', position: 'DEF', nacionality: 'ESP',value: 1200000)
Player.create(name: 'Francisco Javier Chica Torres',shirt: 'Chica', realteam: 'BET', position: 'DEF', nacionality: 'ESP',value: 1800000)
Player.create(name: 'Juan Francisco Moreno Fuertes',shirt: 'Juanfran', realteam: 'BET', position: 'MED', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Javier Torres Buigues',shirt: 'Xavi Torres', realteam: 'BET', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Alfred Ndiaye',shirt: 'Ndiaye', realteam: 'BET', position: 'MED', nacionality: 'SEN',value: 5000000)
Player.create(name: 'Javier Magro Matilla',shirt: 'Matilla', realteam: 'BET', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'José Antonio Delgado Villar',shirt: 'Nono', realteam: 'BET', position: 'MED', nacionality: 'ESP',value: 800000)
Player.create(name: 'Emmanuel Nosakhare Igiebor',shirt: 'Nosa', realteam: 'BET', position: 'MED', nacionality: 'NIG',value: 1500000)
Player.create(name: 'Lorenzo Enrique Reyes Vicencio',shirt: 'Reyes', realteam: 'BET', position: 'MED', nacionality: 'CHI',value: 1000000)
Player.create(name: 'Joan Verdú Fernández',shirt: 'Verdú', realteam: 'BET', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Salvador Sevilla López',shirt: 'Salva Sevilla', realteam: 'BET', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Álvaro Vadillo Cifuentes',shirt: 'Vadillo', realteam: 'BET', position: 'MED', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Juan Carlos Pérez López',shirt: 'Juan Carlos', realteam: 'BET', position: 'MED', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Cedric Mabwati Gerard',shirt: 'Cedric', realteam: 'BET', position: 'MED', nacionality: 'RDC',value: 1500000)
Player.create(name: 'Rubén Castro Martín',shirt: 'Rubén Castro', realteam: 'BET', position: 'DEL', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Leonardo Carrilho Baptistao',shirt: 'Leo Baptistao', realteam: 'BET', position: 'DEL', nacionality: 'BRA',value: 6000000)
Player.create(name: 'Manuel Jesús Vázquez Florido',shirt: 'Chuli', realteam: 'BET', position: 'DEL', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Jorge Molina Vidal',shirt: 'Jorge Molina', realteam: 'BET', position: 'DEL', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Sergio Asenjo Andrés',shirt: 'Sergio Asenjo', realteam: 'VIL', position: 'POR', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Juan Carlos Sánchez Martínez',shirt: 'Juan Carlos', realteam: 'VIL', position: 'POR', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Mateo Pablo Musacchio',shirt: 'Musacchio', realteam: 'VIL', position: 'DEF', nacionality: 'ARG',value: 6000000)
Player.create(name: 'José Antonio Dorado Ramírez',shirt: 'Dorado', realteam: 'VIL', position: 'DEF', nacionality: 'ESP',value: 800000)
Player.create(name: 'Gabriel Armando de Abreu',shirt: 'Gabriel Paulista', realteam: 'VIL', position: 'DEF', nacionality: 'BRA',value: 1500000)
Player.create(name: 'Pablo Íñiguez de Heredia Larraz',shirt: 'Pablo Íñiguez', realteam: 'VIL', position: 'DEF', nacionality: 'ESP',value: 900000)
Player.create(name: 'Bojan Jokic',shirt: 'Jokic', realteam: 'VIL', position: 'DEF', nacionality: 'ESL',value: 600000)
Player.create(name: 'Jaume Vicent Costa Jordà',shirt: 'Jaume Costa', realteam: 'VIL', position: 'DEF', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Mario Gaspar Pérez Martínez',shirt: 'Mario Gaspar', realteam: 'VIL', position: 'DEF', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Aleksandr Pantic',shirt: 'Pantic', realteam: 'VIL', position: 'DEF', nacionality: 'SER',value: 900000)
Player.create(name: 'Bruno Soriano Llido',shirt: 'Bruno', realteam: 'VIL', position: 'MED', nacionality: 'ESP',value: 7000000)
Player.create(name: 'Tomás Pina Isla',shirt: 'Pina', realteam: 'VIL', position: 'MED', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Rubén Gracia Calamache',shirt: 'Cani', realteam: 'VIL', position: 'MED', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Manuel Trigueros Muñoz',shirt: 'Manu Trigueros', realteam: 'VIL', position: 'MED', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Óliver Torres Muñoz',shirt: 'Óliver Torres', realteam: 'VIL', position: 'MED', nacionality: 'ESP',value: 8000000)
Player.create(name: 'Moisés Gómez Bordonado',shirt: 'Moi Gómez', realteam: 'VIL', position: 'MED', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Joan Angel Román Ollé',shirt: 'Joan Román', realteam: 'VIL', position: 'MED', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Javier Ignacio Aquino Carmona',shirt: 'Aquino', realteam: 'VIL', position: 'MED', nacionality: 'MEX',value: 3000000)
Player.create(name: 'Giovani Álex do Santos Ramírez',shirt: 'Gio', realteam: 'VIL', position: 'DEL', nacionality: 'MEX',value: 10000000)
Player.create(name: 'Jeremy Perbet',shirt: 'Perbet', realteam: 'VIL', position: 'DEL', nacionality: 'FRA',value: 2500000)
Player.create(name: 'Ikechukwu Uche',shirt: 'Uche', realteam: 'VIL', position: 'DEL', nacionality: 'NIG',value: 3000000)
Player.create(name: 'Jonathan Pereira Rodríguez',shirt: 'Jonathan Pereira', realteam: 'VIL', position: 'DEL', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Javier Varas Herrera',shirt: 'Javi Varas', realteam: 'SEV', position: 'POR', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Antonio Alberto Bastos Pimparel',shirt: 'Beto', realteam: 'SEV', position: 'POR', nacionality: 'POR',value: 4000000)
Player.create(name: 'Federico Julián Fazio',shirt: 'Fazio', realteam: 'SEV', position: 'DEF', nacionality: 'ARG',value: 6000000)
Player.create(name: 'Daniel Filipe Martins Carriço',shirt: 'Carriço', realteam: 'SEV', position: 'DEF', nacionality: 'POR',value: 3000000)
Player.create(name: 'Nicolás Martín Pareja',shirt: 'Pareja', realteam: 'SEV', position: 'DEF', nacionality: 'ARG',value: 2500000)
Player.create(name: 'Fernando Navarro Corbacho',shirt: 'Fernando Navarro', realteam: 'SEV', position: 'DEF', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Alberto Moreno Pérez',shirt: 'Moreno', realteam: 'SEV', position: 'DEF', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Diogo José Rosário Gomes Figueiras',shirt: 'Diogo Figueiras', realteam: 'SEV', position: 'POR', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Jorge Andujar Moreno',shirt: 'Coke', realteam: 'SEV', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Alex Sandro Mendoça dos Santos',shirt: 'Cicinho', realteam: 'SEV', position: 'DEF', nacionality: 'BRA',value: 2500000)
Player.create(name: 'Vicente Iborra de la Fuente',shirt: 'Iborra', realteam: 'SEV', position: 'MED', nacionality: 'ESP',value: 6000000)
Player.create(name: 'Stéphane Mbia Etoundi',shirt: 'Mbia', realteam: 'SEV', position: 'MED', nacionality: 'CAM',value: 9000000)
Player.create(name: 'Sebastián Carlos Cristóforo Pepe',shirt: 'Cristóforo', realteam: 'MED', position: 'DEL', nacionality: 'URU',value: 1000000)
Player.create(name: 'Ivan Rakitic',shirt: 'Rakitic', realteam: 'SEV', position: 'MED', nacionality: 'CRO',value: 20000000)
Player.create(name: 'Piotr Artur Trochowski',shirt: 'Trochowski', realteam: 'SEV', position: 'MED', nacionality: 'ALE',value: 3000000)
Player.create(name: 'Marko Marin',shirt: 'Marin', realteam: 'SEV', position: 'MED', nacionality: 'ALE',value: 5000000)
Player.create(name: 'Víctor Machín Pérez',shirt: 'Vitolo', realteam: 'SEV', position: 'MED', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Denis Tcheryshev',shirt: 'Tcheryshev', realteam: 'SEV', position: 'MED', nacionality: 'RUS',value: 5000000)
Player.create(name: 'José Antonio Reyes Calderón',shirt: 'Reyes', realteam: 'SEV', position: 'MED', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Jairo Samperio Bustara',shirt: 'Jairo', realteam: 'SEV', position: 'DEL', nacionality: 'ESP',value: 3500000)
Player.create(name: 'Carlos Arturo Bacca Ahumada',shirt: 'Bacca', realteam: 'SEV', position: 'DEL', nacionality: 'COL',value: 10000000)
Player.create(name: 'Kévin Gameiro',shirt: 'Gameiro', realteam: 'SEV', position: 'DEL', nacionality: 'FRA',value: 7000000)
Player.create(name: 'Carlos Idriss Kameni',shirt: 'Kameni', realteam: 'MGA', position: 'DEL', nacionality: 'CAM',value: 1000000)
Player.create(name: 'Wilfredo Daniel Caballero',shirt: 'Caballero', realteam: 'MGA', position: 'DEL', nacionality: 'ARG',value: 5000000)
Player.create(name: 'Weligton Róbson Pereira da Silva',shirt: 'Weligton', realteam: 'MGA', position: 'DEF', nacionality: 'BRA',value: 1000000)
Player.create(name: 'Flávio Nunes Ferreira',shirt: 'Flávio Ferreira', realteam: 'MGA', position: 'DEF', nacionality: 'POR',value: 1000000)
Player.create(name: 'Marcos Alberto Angeleri',shirt: 'Angeleri', realteam: 'MGA', position: 'DEF', nacionality: 'ARG',value: 1000000)
Player.create(name: 'Sergio Sánchez Ortega',shirt: 'Sergio Sánchez', realteam: 'MGA', position: 'DEF', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Vitorino Gabriel Pacheco Antunes',shirt: 'Antunes', realteam: 'MGA', position: 'DEF', nacionality: 'POR',value: 3000000)
Player.create(name: 'José Manuel Casado Bizcocho',shirt: 'Casado', realteam: 'MGA', position: 'DEF', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Jesús Gámez Duarte',shirt: 'Jesús Ǵámez', realteam: 'MGA', position: 'DEF', nacionality: 'ESP',value: 6000000)
Player.create(name: 'Ignacio Camacho Barnola',shirt: 'Ignacio Camacho', realteam: 'MGA', position: 'DEL', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Pablo Javier Pérez',shirt: 'Pablo Pérez', realteam: 'MGA', position: 'MED', nacionality: 'ARG',value: 1500000)
Player.create(name: 'Fernando Damián Tissone Rodrigues',shirt: 'Tissone', realteam: 'MGA', position: 'MED', nacionality: 'ARG',value: 2500000)
Player.create(name: 'Sergi Darder Moll',shirt: 'Darder', realteam: 'MGA', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Sérgio Paulo Barbosa Valente',shirt: 'Duda', realteam: 'MGA', position: 'MED', nacionality: 'POR',value: 1800000)
Player.create(name: 'Eliseu Pereira dos Santos',shirt: 'Eliseu', realteam: 'MGA', position: 'MED', nacionality: 'POR',value: 3000000)
Player.create(name: 'Francisco Portillo Soler',shirt: 'Portillo', realteam: 'MGA', position: 'MED', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Oleksandr Iakovenko',shirt: 'Iakovenko', realteam: 'MGA', position: 'MED', nacionality: 'UCR',value: 1800000)
Player.create(name: 'Nordin Amrabat',shirt: 'Amrabat', realteam: 'MGA', position: 'MED', nacionality: 'MAR',value: 4000000)
Player.create(name: 'Bartolomiej Pawlowski',shirt: 'Pawlowski', realteam: 'MGA', position: 'DEL', nacionality: 'POL',value: 1000000)
Player.create(name: 'Mounir El-Hamdaoui',shirt: 'El Hamdaoui', realteam: 'MGA', position: 'DEL', nacionality: 'MAR',value: 2000000)
Player.create(name: 'Roque Luis Santa Cruz Cantero',shirt: 'Santa Cruz', realteam: 'MGA', position: 'DEL', nacionality: 'PAR',value: 2500000)
Player.create(name: 'Ezequiel Rescaldani',shirt: 'Rescaldani', realteam: 'MGA', position: 'DEL', nacionality: 'ARG',value: 2200000)
Player.create(name: 'Samuel Sánchez García',shirt: 'Samu', realteam: 'MGA', position: 'DEL', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Juan Miguel Jiménez López',shirt: 'Juanmi', realteam: 'MGA', position: 'DEL', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Diego Alves Carreira',shirt: 'Diego Alves', realteam: 'VAL', position: 'POR', nacionality: 'BRA',value: 6000000)
Player.create(name: 'Vicente Guaita Panadero',shirt: 'Guaita', realteam: 'VAL', position: 'POR', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Ruben Miguel Nunes Vezo',shirt: 'Ruben Vezo', realteam: 'VAL', position: 'DEF', nacionality: 'POR',value: 1600000)
Player.create(name: 'Phillipe Sylvain Senderos',shirt: 'Senderos', realteam: 'VAL', position: 'DEF', nacionality: 'SUI',value: 2500000)
Player.create(name: 'Víctor Ruiz Torre',shirt: 'Víctor Ruiz', realteam: 'VAL', position: 'DEF', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Ricardo Miguel Moreira da Costa',shirt: 'Ricardo Costa', realteam: 'VAL', position: 'DEF', nacionality: 'POR',value: 3000000)
Player.create(name: 'Jérémy Mathieu',shirt: 'Mathieu', realteam: 'VAL', position: 'DEF', nacionality: 'FRA',value: 9000000)
Player.create(name: 'Juan Bernat Velasco',shirt: 'Bernat', realteam: 'VAL', position: 'DEF', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Joâo Pedro da Silva Pereira',shirt: 'Joâo Pereira', realteam: 'VAL', position: 'DEF', nacionality: 'POR',value: 6000000)
Player.create(name: 'Antonio Barragán Fernández',shirt: 'Barragán', realteam: 'VAL', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Oriol Romeu Vidal',shirt: 'Oriol Romeu', realteam: 'VAL', position: 'MED', nacionality: 'ESP',value: 7000000)
Player.create(name: 'Javier Fuego Martínez',shirt: 'Javi Fuego', realteam: 'VAL', position: 'MED', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Seydou Keita',shirt: 'Keita', realteam: 'VAL', position: 'MED', nacionality: 'MAL',value: 1500000)
Player.create(name: 'Daniel Parejo Muñoz',shirt: 'Parejo', realteam: 'VAL', position: 'MED', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Miguel Ángel Herrero Javaloyas',shirt: 'Míchel', realteam: 'VAL', position: 'MED', nacionality: 'ESP',value: 3500000)
Player.create(name: 'Pablo Daniel Piatti',shirt: 'Piatti', realteam: 'VAL', position: 'MED', nacionality: 'ARG',value: 4000000)
Player.create(name: 'Federico Nicolás Cartabia',shirt: 'Fede Cartabia', realteam: 'VAL', position: 'ARG', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Soufiane Feghouli',shirt: 'Feghouli', realteam: 'VAL', position: 'MED', nacionality: 'ALG',value: 12000000)
Player.create(name: 'Eduardo Jesús Vargas Rojas',shirt: 'Eduardo Vargas', realteam: 'VAL', position: 'DEL', nacionality: 'CHI',value: 6000000)
Player.create(name: 'Jonas Gonçalves Oliveira',shirt: 'Jonas', realteam: 'VAL', position: 'DEL', nacionality: 'BRA',value: 12000000)
Player.create(name: 'Francisco Alcácer García',shirt: 'Paco Alcácer', realteam: 'VAL', position: 'DEL', nacionality: 'ESP',value: 6000000)
Player.create(name: 'Vinicius Vasconcelos Araújo',shirt: 'Vinicius Araújo', realteam: 'VAL', position: 'DEL', nacionality: 'BRA',value: 3500000)
Player.create(name: 'Gorka Iraizoz Moreno',shirt: 'Iraizoz', realteam: 'ATH', position: 'POR', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Iago Herrerín Buisán',shirt: 'Herrerín', realteam: 'ATH', position: 'POR', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Aymeric Laporte',shirt: 'Laporte', realteam: 'ATH', position: 'DEF', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Mikel San José Domínguez',shirt: 'San José', realteam: 'ATH', position: 'DEF', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Unai Albizua Urquijo',shirt: 'Albizua', realteam: 'ATH', position: 'DEF', nacionality: 'ESP',value: 200000)
Player.create(name: 'Xabier Etxeita Gorritxategui',shirt: 'Etxeita', realteam: 'ATH', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Carlos Gurpegi Nausía',shirt: 'Gurpegi', realteam: 'ATH', position: 'DEF', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Borja Ekiza Imaz',shirt: 'Ekiza', realteam: 'ATH', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'Enric Saborit Teixidor',shirt: 'Saborit', realteam: 'ATH', position: 'DEF', nacionality: 'ESP',value: 400000)
Player.create(name: 'Mikel Balenziaga Oruesagasti',shirt: 'Balenziaga', realteam: 'ATH', position: 'DEF', nacionality: 'ESP',value: 3500000)
Player.create(name: 'Andoni Iraola Sagarna',shirt: 'Iraola', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 6000000)
Player.create(name: 'Erik Morán Arribas',shirt: 'Erik Mórán', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 600000)
Player.create(name: 'Ander Iturraspe Derteano',shirt: 'Iturraspe', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Íñigo Pérez Soto',shirt: 'Íñigo Pérez', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Beñat Etxebarria Urkiaga',shirt: 'Beñat', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 9000000)
Player.create(name: 'Óscar de Marcos Arana',shirt: 'De Marcos', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 8000000)
Player.create(name: 'Mikel Rico Moreno',shirt: 'Mikel Rico', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 8000000)
Player.create(name: 'Ander Herrera Agüera',shirt: 'Ander Herrera', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 20000000)
Player.create(name: 'Ibai Gómez Pérez',shirt: 'Ibai Gómez', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 4500000)
Player.create(name: 'Markel Susaeta Laskurain',shirt: 'Susaeta', realteam: 'ATH', position: 'MED', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Iker Muniain Goñi',shirt: 'Muniain', realteam: 'ATH', position: 'DEL', nacionality: 'ESP',value: 18000000)
Player.create(name: 'Gaizka Toquero Pinedo',shirt: 'Toquero', realteam: 'ATH', position: 'DEL', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Enrique Sola Clemente',shirt: 'Kike Sola', realteam: 'ATH', position: 'DEL', nacionality: 'ESP',value: 4000000)
Player.create(name: 'Aritz Aduriz Zubeldia',shirt: 'Aduriz', realteam: 'ATH', position: 'DEL', nacionality: 'ESP',value: 3500000)
Player.create(name: 'Claudio Andrés Bravo Muñoz',shirt: 'Claudio Bravo', realteam: 'RSO', position: 'POR', nacionality: 'CHI',value: 4000000)
Player.create(name: 'Eñaut Zubikarai Goñi',shirt: 'Zubikarai', realteam: 'RSO', position: 'POR', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Mikel González de Martín Martínez',shirt: 'Mikel González', realteam: 'RSO', position: 'DEL', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Íñigo Martínez Berridi',shirt: 'Íñigo Martínez', realteam: 'RSO', position: 'DEF', nacionality: 'ESP',value: 12000000)
Player.create(name: 'Ion Ansotegui Gorostola',shirt: 'Ansotegui', realteam: 'RSO', position: 'DEF', nacionality: 'ESP',value: 2000000)
Player.create(name: 'José Ángel Valdés Díaz',shirt: 'José Ángel', realteam: 'RSO', position: 'DEF', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Alberto de la Bella Madureño',shirt: 'De la Bella', realteam: 'RSO', position: 'DEF', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Carlos Martínez Díez',shirt: 'Carlos Martínez', realteam: 'RSO', position: 'DEF', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Daniel Estrada Agirrezabalaga',shirt: 'Estrada', realteam: 'RSO', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Gorka Elustondo Urkola',shirt: 'Elustondo', realteam: 'RSO', position: 'MED', nacionality: 'ESP',value: 1400000)
Player.create(name: 'Markel Bergara Larrañaga',shirt: 'Bergara', realteam: 'RSO', position: 'MED', nacionality: 'ESP',value: 2500000)
Player.create(name: 'Rubén Pardo Gutiérrez',shirt: 'Rubén Pardo', realteam: 'RSO', position: 'MED', nacionality: 'ESP',value: 6000000)
Player.create(name: 'David Zurutuza Veillet',shirt: 'Zurutuza', realteam: 'RSO', position: 'MED', nacionality: 'FRA',value: 4000000)
Player.create(name: 'Javier Ros Añón',shirt: 'Javi Ros', realteam: 'RSO', position: 'MED', nacionality: 'ESP',value: 1500000)
Player.create(name: 'Esteban Félix Granero Molina',shirt: 'Granero', realteam: 'RSO', position: 'MED', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Xabier Prieto Argarate',shirt: 'Xabi Prieto', realteam: 'RSO', position: 'MED', nacionality: 'ESP',value: 8000000)
Player.create(name: 'Sergio Canales Madrazo',shirt: 'Sergio Canales', realteam: 'RSO', position: 'MED', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Gonzalo Castro Irizábal',shirt: 'Chory Castro', realteam: 'RSO', position: 'MED', nacionality: 'URU',value: 6000000)
Player.create(name: 'Antoine Griezmann ',shirt: 'Griezmann', realteam: 'RSO', position: 'DEL', nacionality: 'FRA',value: 25000000)
Player.create(name: 'Carlos Alberto Vela Garrido',shirt: 'Vela', realteam: 'RSO', position: 'DEL', nacionality: 'MEX',value: 20000000)
Player.create(name: 'Haris Seferovic',shirt: 'Seferovic', realteam: 'RSO', position: 'DEL', nacionality: 'SUI',value: 4500000)
Player.create(name: 'Imanol Agirretxe Arruti',shirt: 'Agirretxe', realteam: 'RSO', position: 'DEL', nacionality: 'ESP',value: 6000000)
Player.create(name: 'Diego Ifrán Sala',shirt: 'Ifrán', realteam: 'RSO', position: 'DEL', nacionality: 'URU',value: 1500000)
Player.create(name: 'Daniel Aranzubia Aguado',shirt: 'Aranzubia', realteam: 'ATM', position: 'POR', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Thibaut Courtois',shirt: 'Courtois', realteam: 'ATM', position: 'POR', nacionality: 'BEL',value: 25000000)
Player.create(name: 'Diego Roberto Godín Leal',shirt: 'Godín', realteam: 'ATM', position: 'DEF', nacionality: 'URU',value: 20000000)
Player.create(name: 'Tobias Albertine Mauritius Alderweireld',shirt: 'Alderweireld', realteam: 'ATM', position: 'BEL', nacionality: 'URU',value: 10000000)
Player.create(name: 'José María Giménez de Vargas',shirt: 'Jose Giménez', realteam: 'ATM', position: 'DEF', nacionality: 'URU',value: 2000000)
Player.create(name: 'Joâo Miranda de Souza Filho',shirt: 'Miranda', realteam: 'ATM', position: 'DEF', nacionality: 'BRA',value: 15000000)
Player.create(name: 'Luis Filipe Kasmirski',shirt: 'Filipe Luis', realteam: 'ATM', position: 'DEF', nacionality: 'BRA',value: 15000000)
Player.create(name: 'Emiliano Adrián Insúa Zapata',shirt: 'Insúa', realteam: 'ATM', position: 'DEF', nacionality: 'ARG',value: 5000000)
Player.create(name: 'Javier Manquillo Gaitán',shirt: 'Manquillo', realteam: 'ATM', position: 'DEF', nacionality: 'ESP',value: 6000000)
Player.create(name: 'Juan Francisco Torres Belén',shirt: 'Juanfran', realteam: 'ATM', position: 'DEF', nacionality: 'ESP',value: 14000000)
Player.create(name: 'Mario Suárez Mata',shirt: 'Mario Suárez', realteam: 'ATM', position: 'MED', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Tiago Cardoso Mendes',shirt: 'Tiago', realteam: 'ATM', position: 'MED', nacionality: 'POR',value: 3000000)
Player.create(name: 'Gabriel Fernández Arenas',shirt: 'Gabi', realteam: 'ATM', position: 'MED', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Jorge Resurrección Merodio',shirt: 'Koke', realteam: 'ATM', position: 'MED', nacionality: 'ESP',value: 25000000)
Player.create(name: 'Raúl García Escudero',shirt: 'Raúl García', realteam: 'ATM', position: 'MED', nacionality: 'ESP',value: 12000000)
Player.create(name: 'Diego Ribas da Cunha',shirt: 'Diego', realteam: 'ATM', position: 'MED', nacionality: 'BRA',value: 12000000)
Player.create(name: 'Arda Turan',shirt: 'Arda Turan', realteam: 'ATM', position: 'MED', nacionality: 'TUR',value: 25000000)
Player.create(name: 'Cristian Gabriel Rodríguez Barotti',shirt: 'Cebolla Rodríguez', realteam: 'ATM', position: 'MED', nacionality: 'URU',value: 5000000)
Player.create(name: 'José Ernesto Sosa',shirt: 'Sosa', realteam: 'ATM', position: 'DEL', nacionality: 'ARG',value: 9000000)
Player.create(name: 'Adrián López Álvarez',shirt: 'Adrián', realteam: 'ATM', position: 'DEL', nacionality: 'ESP',value: 8000000)
Player.create(name: 'David Villa Sánchez',shirt: 'David Villa', realteam: 'ATM', position: 'DEL', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Diego da Silva Costa',shirt: 'Diego Costa', realteam: 'ATM', position: 'DEL', nacionality: 'ESP',value: 30000000)
Player.create(name: 'Iker Casillas Fernández',shirt: 'Iker Casillas', realteam: 'RMD', position: 'POR', nacionality: 'ESP',value: 12000000)
Player.create(name: 'Diego López Rodríguez',shirt: 'Diego López', realteam: 'RMD', position: 'POR', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Raphäel Varane',shirt: 'Varane', realteam: 'RMD', position: 'DEF', nacionality: 'FRA',value: 24000000)
Player.create(name: 'Képler Laveran Lima Ferreira',shirt: 'Pepe', realteam: 'RMD', position: 'DEF', nacionality: 'POR',value: 18000000)
Player.create(name: 'Sergio Ramos García',shirt: 'Śergio Ramos', realteam: 'RMD', position: 'DEF', nacionality: 'ESP',value: 40000000)
Player.create(name: 'Jose Ignacio Fernández Iglesias',shirt: 'Nacho Fernández', realteam: 'RMD', position: 'ESP', nacionality: 'ESP',value: 5000000)
Player.create(name: 'Fábio Alexandre da Silva Coentrâo',shirt: 'Coentrâo', realteam: 'RMD', position: 'DEF', nacionality: 'POR',value: 14000000)
Player.create(name: 'Marcelo Vieira da Silva Junior',shirt: 'Marcelo', realteam: 'RMD', position: 'DEF', nacionality: 'BRA',value: 25000000)
Player.create(name: 'Daniel Carvajal Ramos',shirt: 'Carvajal', realteam: 'RMD', position: 'DEF', nacionality: 'ESP',value: 12000000)
Player.create(name: 'Álvaro Arbeloa Coca',shirt: 'Arbeloa', realteam: 'RMD', position: 'DEF', nacionality: 'ESP',value: 7000000)
Player.create(name: 'Sami Khedira',shirt: 'Khedira', realteam: 'RMD', position: 'MED', nacionality: 'ALE',value: 22000000)
Player.create(name: 'Carlos Henrique Casemiro',shirt: 'Casemiro', realteam: 'MED', position: 'DEL', nacionality: 'BRA',value: 6000000)
Player.create(name: 'Xabier Alonso Olona',shirt: 'Xabi Alonso', realteam: 'MED', position: 'DEL', nacionality: 'ESP',value: 12000000)
Player.create(name: 'Luka Modric',shirt: 'Modric', realteam: 'RMD', position: 'MED', nacionality: 'CRO',value: 40000000)
Player.create(name: 'Asier Illarramendi Andonegu',shirt: 'Illarramendi', realteam: 'RMD', position: 'MED', nacionality: 'ESP',value: 18000000)
Player.create(name: 'Francisco Román Alarcón Suárez',shirt: 'Isco', realteam: 'RMD', position: 'DEL', nacionality: 'ESP',value: 35000000)
Player.create(name: 'Gareth Frank Bale',shirt: 'Bale', realteam: 'RMD', position: 'MED', nacionality: 'GAL',value: 80000000)
Player.create(name: 'Ángel Fabián di María',shirt: 'Di María', realteam: 'RMD', position: 'MED', nacionality: 'ARG',value: 30000000)
Player.create(name: 'Cristiano Ronaldo dos Santos Aveiro',shirt: 'Cristiano Ronaldo', realteam: 'RMD', position: 'DEL', nacionality: 'POR',value: 100000000)
Player.create(name: 'Jesé Rodríguez Ruiz',shirt: 'Jesé', realteam: 'RMD', position: 'DEL', nacionality: 'ESP',value: 15000000)
Player.create(name: 'Karim Benzema',shirt: 'Benzema', realteam: 'RMD', position: 'DEL', nacionality: 'FRA',value: 34000000)
Player.create(name: 'Álvaro Borja Morata Martín',shirt: 'Morata', realteam: 'RMD', position: 'DEL', nacionality: 'ESP',value: 12000000)
Player.create(name: 'Víctor Valdés Arribas',shirt: 'Víctor Valdés', realteam: 'FCB', position: 'POR', nacionality: 'ESP',value: 12000000)
Player.create(name: 'José Manuel Pinto Colorado',shirt: 'Pinto', realteam: 'FCB', position: 'POR', nacionality: 'ESP',value: 300000)
Player.create(name: 'Gerard Piqué Bernabeu',shirt: 'Piqué', realteam: 'FCB', position: 'DEF', nacionality: 'ESP',value: 36000000)
Player.create(name: 'Carles Puyol Saforcada',shirt: 'Puyol', realteam: 'FCB', position: 'DEF', nacionality: 'ESP',value: 1000000)
Player.create(name: 'Javier Alejandro Mascherano',shirt: 'Mascherano', realteam: 'FCB', position: 'DEF', nacionality: 'ARG',value: 15000000)
Player.create(name: 'Marc Bartra Aragall',shirt: 'Bartra', realteam: 'FCB', position: 'DEF', nacionality: 'ESP',value: 12000000)
Player.create(name: 'Jordi Alba Ramos',shirt: 'Jordi Alba', realteam: 'FCB', position: 'DEF', nacionality: 'ESP',value: 25000000)
Player.create(name: 'Adriano Correia Claro',shirt: 'Adriano', realteam: 'FCB', position: 'DEF', nacionality: 'BRA',value: 15000000)
Player.create(name: 'Martín Montoya Torralbo',shirt: 'Montoya', realteam: 'FCB', position: 'DEF', nacionality: 'ESP',value: 12000000)
Player.create(name: 'Daniel Alves da Silva',shirt: 'Dani Alves', realteam: 'FCB', position: 'DEF', nacionality: 'BRA',value: 18000000)
Player.create(name: 'Sergio Busquets i Burgos',shirt: 'Sergi Busquets', realteam: 'FCB', position: 'MED', nacionality: 'ESP',value: 45000000)
Player.create(name: 'Alexandre Song-Billong',shirt: 'Alex Song', realteam: 'FCB', position: 'MED', nacionality: 'CAM',value: 18000000)
Player.create(name: 'Xavier Hernández Creus',shirt: 'Xavi', realteam: 'FCB', position: 'MED', nacionality: 'ESP',value: 10000000)
Player.create(name: 'Andrés Iniesta Luján',shirt: 'Iniesta', realteam: 'FCB', position: 'MED', nacionality: 'ESP',value: 55000000)
Player.create(name: 'Jonathan dos Santos Ramírez',shirt: 'Jonathan', realteam: 'FCB', position: 'MED', nacionality: 'MEX',value: 3000000)
Player.create(name: 'Sergi Roberto Carnicer',shirt: 'Sergi Roberto', realteam: 'FCB', position: 'MED', nacionality: 'ESP',value: 8000000)
Player.create(name: 'Francesc Fabregas Soler',shirt: 'Cesc', realteam: 'FCB', position: 'MED', nacionality: 'ESP',value: 50000000)
Player.create(name: 'Ibrahim Afellay',shirt: 'Afellay', realteam: 'FCB', position: 'MED', nacionality: 'HOL',value: 5000000)
Player.create(name: 'Neymar da Silva Santos Junior',shirt: 'Neymar', realteam: 'FCB', position: 'DEL', nacionality: 'BRA',value: 60000000)
Player.create(name: 'Cristian Tello Herrera',shirt: 'Tello', realteam: 'FCB', position: 'DEL', nacionality: 'ESP',value: 9000000)
Player.create(name: 'Pedro Eliezer Rodríguez Ledesma',shirt: 'Pedro', realteam: 'FCB', position: 'DEL', nacionality: 'ESP',value: 25000000)
Player.create(name: 'Alexis Alejandro Sánchez Sánchez',shirt: 'Alexis Sánchez', realteam: 'FCB', position: 'DEL', nacionality: 'CHI',value: 30000000)
Player.create(name: 'Juan Isaac Cuenca López',shirt: 'Cuenca', realteam: 'FCB', position: 'DEL', nacionality: 'ESP',value: 3000000)
Player.create(name: 'Lionel Andrés Messi Cuccitini',shirt: 'Messi', realteam: 'FCB', position: 'DEL', nacionality: 'ARG',value: 120000000)
